# Loader Settings
modLoader="javafml"
loaderVersion="${loader_version_range}"

# Mod Settings
license="${mod_license}"
issueTrackerURL="${mod_issue}"
[[mods]]
  modId       = "${mod_id}"
  displayName = "${mod_name}"
  version     = "${mod_version}"
  authors     = "${mod_authors}"
  credits     = "${mod_credits}"
  logoFile    = "${mod_id}.png"
  displayURL  = "${mod_url}"
  description = '''${mod_description}'''

[[mixins]]
  config = "${mod_id}.mixins.json"

[[accessTransformers]]
  file = "META-INF/accesstransformer.cfg"

# NeoForge Dependency
[[dependencies."${mod_id}"]]
  modId        = "neoforge"
  # "required", "optional", "incompatible", "discouraged"
  type         = "required"
  versionRange = "${neo_version_range}"
  ordering     = "NONE"
  side         = "BOTH"

# Minecraft Dependency
[[dependencies."${mod_id}"]]
  modId="minecraft"
  type="required"
  versionRange="${minecraft_version_range}"
  ordering="NONE"
  side="BOTH"

# Iron's Spells'n Spellbooks Dependency
[[dependencies."${mod_id}"]]
  modId="irons_spellbooks"
  type="required"
  versionRange="[1.21.1-3.15.0,)"
  ordering="NONE"
  side="BOTH"